# Generated by Django 2.1.7 on 2019-07-16 02:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190312_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catalog',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
